name       : fuse2
version    : 2.9.9
release    : 18
source     :
    - https://github.com/libfuse/libfuse/releases/download/fuse-2.9.9/fuse-2.9.9.tar.gz : d0e69d5d608cc22ff4843791ad097f554dd32540ddc9bed7638cc6fea7c1b4b5
license    : LGPL-2.0-only
component  : system.utils
summary    : File Systems in User Space
description: |
    File Systems in User Space
rundeps    :
    - fuse-common
environment:
    export UDEV_RULES_PATH=%libdir%/udev/rules.d
setup      : |
    sed -i 's|mknod|echo Disabled: mknod |g' util/Makefile.in
    %patch -p1 < $pkgfiles/0001-fusermount-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/util-ulockmgr_server.c-conditionally-define-closefrom.patch

    %reconfigure --disable-static --enable-util
build      : |
    %make
install    : |
    %make_install
    
    rm -rfv $installdir/dev
    rm -rfv $installdir/etc/
